### ISSUE TITLE
Restrict permissions

### ISSUE THREAD

**Issue by stefanbuck** [Frozenfire92/Pages2Repo#10]
If possible, limit the permission to `https://*.github.io/*` and `https://github.com/*`.

![screen shot 2015-06-07 at 18 43 04](https://cloud.githubusercontent.com/assets/1393946/8024907/116f7850-0d45-11e5-9f3a-f629c9ccf4c0.png)

**Comment by Frozenfire92** [comment]
Thanks, forgot to change this. Pushed to the chrome webstore, could take an hour before its updated on there

**Comment by stefanbuck** [comment]
:+1:
