### ISSUE TITLE
Stayed signed

### ISSUE THREAD

**Issue by Johann-S** [Frozenfire92/Pages2Repo#12]
When I found a page with a github repo I always have to sign up if the token as expired.

Why not using a token added in https://github.com/settings/tokens  to stay signed up ?

**Comment by Frozenfire92** [comment]
This is a great idea, the only issue I foresee is if a user doesn't enable the right permissions, however where the sign in page is now putting that in  as a screenshot could alleviate this.

I haven't had to sign in multiple times yet ( #6 ), do you by chance know how long the tokens are valid for? I wasn't able to find this in the documentation

**Comment by Johann-S** [comment]
No I'm not sure about how long a token expire but I've to sign in once a day.

I know it's possible to open a page to add a token with the correct permission pre selected.
It's already done by Github Notifier (https://github.com/sindresorhus/github-notifier-chrome)

**Comment by Frozenfire92** [comment]
Ok cool,

I noticed you forked it, if you plan on working on this let me know, if not I will have time to this weekend :)

**Comment by Johann-S** [comment]
I'll try but it's the first time I work on a chrome extension so I'm not sure to do it very well

**Comment by Johann-S** [comment]
I don't know what permissions are needed 
![edit personal access token - google chrome](https://cloud.githubusercontent.com/assets/1689750/8140598/5160003a-115d-11e5-88a4-166a62d75b62.jpg)

**Comment by Frozenfire92** [comment]
The scope as is is blank, so I would try no permissions first to match
that. If that didn't work I would guess public_repo. Let me know how it
goes, will have a chance to look at it tomorrow

**Comment by Frozenfire92** [comment]
I've implemented this, looking into #9 then will release a new version later today. Thanks for the feedback / idea!

**Comment by Frozenfire92** [comment]
It is published, could take an hour before the chrome webstore updates. Thanks!

**Comment by Johann-S** [comment]
Nice work !
Sorry I hadn't time this weekend to work on it.

Do you have interest about using GruntJS with JSCS and using Travis for you futur release ?

**Comment by Frozenfire92** [comment]
I've implemented Gruntjs for the release in #9 I don't think I will be implementing Travis as I don't really think there is a good way to test extensions from the command line

**Comment by Johann-S** [comment]
Sure but you can add JSCS to your GruntJS to check for each contribution the contributor respect your code style

**Comment by Johann-S** [comment]
It works very well thank you !
